### ISSUE TITLE
Unable to locate message source for category 'sprout-email'

### ISSUE THREAD

**Issue by davist11** [barrelstrength/craft-sprout-import#81]
### Description
I'm getting the following error:

```
yii\base\InvalidConfigException: Unable to locate message source for category 'sprout-email'. in /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/i18n/I18N.php:201
Stack trace:
#0 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/i18n/I18N.php(89): yii\i18n\I18N->getMessageSource('sprout-email')
#1 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/i18n/I18N.php(327): yii\i18n\I18N->translate('sprout-email', 'Generate Seed d...', Array, 'en-US')
#2 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/BaseYii.php(526): craft\i18n\I18N->translate('sprout-email', 'Generate Seed d...', Array, 'en-US')
#3 /var/www/bdi/staging/releases/20190401114834/vendor/barrelstrength/sprout-import/src/SproutImport.php(168): yii\BaseYii::t('sprout-email', 'Generate Seed d...')
#4 /var/www/bdi/staging/releases/20190401114834/vendor/barrelstrength/sprout-import/src/SproutImport.php(88): barrelstrength\sproutimport\SproutImport->getUserPermissions()
#5 [internal function]: barrelstrength\sproutimport\SproutImport->barrelstrength\sproutimport\{closure}(Object(craft\events\RegisterUserPermissionsEvent))
#6 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Object(Closure), Object(craft\events\RegisterUserPermissionsEvent))
#7 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'registerPermiss...', Object(craft\events\RegisterUserPermissionsEvent))
#8 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/services/UserPermissions.php(216): yii\base\Component->trigger('registerPermiss...', Object(craft\events\RegisterUserPermissionsEvent))
#9 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/services/UserPermissions.php(231): craft\services\UserPermissions->getAllPermissions()
#10 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Extension/CoreExtension.php(1681): craft\services\UserPermissions->getAssignablePermissions(NULL)
#11 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/helpers/Template.php(79): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\UserPermissions), 'getAssignablePe...', Array, 'method', false, false)
#12 /var/www/bdi/staging/shared/storage/runtime/compiled_templates/be/be52d4b0ba246ac66a276758789b9e6d88466ef19178883db8e8e669e38b24e9.php(64): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\services\UserPermissions), 'getAssignablePe...', Array, 'method')
#13 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(379): __TwigTemplate_050b71778d7c5884b706c81f818881ac211236f73b1c59fd47bd0c1941353d39->doDisplay(Array, Array)
#14 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#15 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#16 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#17 /var/www/bdi/staging/shared/storage/runtime/compiled_templates/a8/a8b13c0cd1d56422bf4cd6a6b5b431daceed4c5c416ec41a0f0bf93076a8a788.php(414): craft\web\twig\Template->display(Array)
#18 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(184): __TwigTemplate_f05316b428267bf1ff92d5209a7f342ab0e56efec87567e1e7fca5c06a4f6153->block_content(Array, Array)
#19 /var/www/bdi/staging/shared/storage/runtime/compiled_templates/ac/ac1ba2f2b9f3d6522aba213b3b719b96e5ee908af248e888b06416a229acb9f0.php(660): Twig\Template->displayBlock('content', Array, Array)
#20 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(184): __TwigTemplate_b9be4ec1dd62d7b1ffaeeb1d9e8abddaeefb6b97be06bd6d9b813e9f600a9011->block_main(Array, Array)
#21 /var/www/bdi/staging/shared/storage/runtime/compiled_templates/ac/ac1ba2f2b9f3d6522aba213b3b719b96e5ee908af248e888b06416a229acb9f0.php(545): Twig\Template->displayBlock('main', Array, Array)
#22 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(184): __TwigTemplate_b9be4ec1dd62d7b1ffaeeb1d9e8abddaeefb6b97be06bd6d9b813e9f600a9011->block_body(Array, Array)
#23 /var/www/bdi/staging/shared/storage/runtime/compiled_templates/22/22e357bf96035e7738d7094f1703067dfedd0e635efe9788b634eda10a8ae54f.php(72): Twig\Template->displayBlock('body', Array, Array)
#24 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(379): __TwigTemplate_be1475182cba40606e18ba4c806e9af8dde3ba1da3a1614c7cc8e561419a1212->doDisplay(Array, Array)
#25 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#28 /var/www/bdi/staging/shared/storage/runtime/compiled_templates/5d/5d419cf5e93e3a178f0cb2f50676cce26986b029c60a5c5cc6bae88d1ccd2a2c.php(52): craft\web\twig\Template->display(Array, Array)
#29 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(379): __TwigTemplate_d4bd8b68d8ca499b3ab3d650041f36ae43f5f8a2e8fabbd414ce1b031092bb9d->doDisplay(Array, Array)
#30 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#31 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#32 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#33 /var/www/bdi/staging/shared/storage/runtime/compiled_templates/ac/ac1ba2f2b9f3d6522aba213b3b719b96e5ee908af248e888b06416a229acb9f0.php(107): craft\web\twig\Template->display(Array, Array)
#34 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(379): __TwigTemplate_b9be4ec1dd62d7b1ffaeeb1d9e8abddaeefb6b97be06bd6d9b813e9f600a9011->doDisplay(Array, Array)
#35 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#36 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#37 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#38 /var/www/bdi/staging/shared/storage/runtime/compiled_templates/a8/a8b13c0cd1d56422bf4cd6a6b5b431daceed4c5c416ec41a0f0bf93076a8a788.php(113): craft\web\twig\Template->display(Array, Array)
#39 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(379): __TwigTemplate_f05316b428267bf1ff92d5209a7f342ab0e56efec87567e1e7fca5c06a4f6153->doDisplay(Array, Array)
#40 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#41 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(356): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#42 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#43 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Template.php(364): craft\web\twig\Template->display(Array)
#44 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#45 /var/www/bdi/staging/releases/20190401114834/vendor/twig/twig/src/Environment.php(319): Twig\TemplateWrapper->render(Array)
#46 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('users/_edit', Array)
#47 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('users/_edit', Array)
#48 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('users/_edit', Array)
#49 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/controllers/UsersController.php(899): craft\web\Controller->renderTemplate('users/_edit', Array)
#50 [internal function]: craft\controllers\UsersController->actionEditUser(NULL, Object(craft\elements\User), NULL)
#51 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#52 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#53 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-user', Array)
#54 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-user', Array)
#55 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('users/edit-user', Array)
#56 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('users/edit-user', Array)
#57 /var/www/bdi/staging/releases/20190401114834/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#58 /var/www/bdi/staging/releases/20190401114834/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#59 /var/www/bdi/staging/releases/20190401114834/public/index.php(21): yii\base\Application->run()
#60 {main}
```

### Steps to reproduce

1. Visit /admin/users/new

### Additional info

- Craft version: Craft Pro 3.1.20.1
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7.25
- Plugins & versions:

<table class="data fullwidth fixed-layout" dir="ltr">
            <tbody>
                                    <tr>
                        <th class="light">Amazon S3</th>
                        <td>1.2.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Asset Rev</th>
                        <td>6.0.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Authorize.net for Craft Commerce</th>
                        <td>1.0.3</td>
                    </tr>
                                    <tr>
                        <th class="light">Campaign Monitor Service</th>
                        <td>1.0.6</td>
                    </tr>
                                    <tr>
                        <th class="light">Cookies</th>
                        <td>1.1.11</td>
                    </tr>
                                    <tr>
                        <th class="light">Craft Commerce</th>
                        <td>2.1.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Dimensions</th>
                        <td>2.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Environment Label</th>
                        <td>3.1.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Inlin</th>
                        <td>2.1.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Pricing Tiers</th>
                        <td>1.1.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Redactor</th>
                        <td>2.3.2</td>
                    </tr>
                                    <tr>
                        <th class="light">Retour</th>
                        <td>3.1.7</td>
                    </tr>
                                    <tr>
                        <th class="light">Sentry</th>
                        <td>1.5.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Sidebar Toggle</th>
                        <td>2.0.0</td>
                    </tr>
                                    <tr>
                        <th class="light">Smart Map</th>
                        <td>3.2.1</td>
                    </tr>
                                    <tr>
                        <th class="light">Spoon</th>
                        <td>3.3.5</td>
                    </tr>
                                    <tr>
                        <th class="light">Sprout Fields</th>
                        <td>3.2.8</td>
                    </tr>
                                    <tr>
                        <th class="light">Sprout Forms</th>
                        <td>3.0.0-beta.49</td>
                    </tr>
                                    <tr>
                        <th class="light">Sprout Import</th>
                        <td>1.0.0-beta.23</td>
                    </tr>
                                    <tr>
                        <th class="light">Sprout Reports</th>
                        <td>1.1.4</td>
                    </tr>
                                    <tr>
                        <th class="light">Video Embed</th>
                        <td>1.2.1</td>
                    </tr>
                            </tbody>
        </table>

**Comment by BenParizek** [comment]
@davist11 This should be resolved in Sprout Import v1.0.0-beta.25.

That said, I'll be notifying users that we will be retiring Sprout Import later this week. Craft recently [acquired FeedMe](https://craftcms.com/blog/feed-me) and we'll be adding FeedMe support to all of our Sprout plugins. 

We'll continue to offer basic support for existing Sprout Import licenses, but will not be selling any further licenses shortly and recommending folks move to FeedMe for anything that's not a small bugfix moving forward.
